# Generated by Django 3.1.4 on 2021-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureApp', '0004_photo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.CharField(default='AnonymousUser', max_length=15),
        ),
    ]
