# Generated by Django 3.1.4 on 2021-05-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictureApp', '0007_multipilephotos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipilePhotos',
        ),
    ]
